### ISSUE TITLE
we need a 'quick-start' document

### ISSUE THREAD

**Issue by ansuz** [hyperboria/docs#19]
the front page should link to it from a conspicuous location. It should contain the following details:

1. a list of system-specific install guides for various linux distros (including android and *WRT), OSX/BSDs, and Windows.
2. A section or a link to another document on the syntax and semantics of cjdroute.conf
3. An explanation of current peering procedures:
  + autopeering (generic)
  + Public peers (for hyperboria)
  + and manual UDP peering, with explanations for the difference between IPv4 and IPv6 configuration blocks.

**Comment by ansuz** [comment]
It should also contain sections on troubleshooting the build process:

1. about seccomp
2. effective bug/error reporting and how to get help
3. system quirks, how to enable ipv6 system-wide and for various browsers

Furthermore, we should explain what is on the network

1. HypeIRC, for development purposes (link to relevant channels (#cjdns, #documentation)
2. an up to date list of popular resources on the network (this is always a problem)
3. an explanation of what we are using for DNS (most people think hypeDNS still exists)
4. how to stay up to date (maybe with a list of RSS/atom/similar feed protocols that are provided by independent sites?

**Comment by bitonator** [comment]
Hi Ansuz,

Check https://github.com/bitonator/docs/blob/quickstart/quickstart.md and let me know what you think.

- Maha

**Comment by ansuz** [comment]
Looks great!

A few little things:

Did you get chrome to work? Last time I checked there were issues because of [this ~~bug~~ feature](https://code.google.com/p/chromium/issues/detail?id=259940).

re: 

> See you at Hyperboria!

I'd `s/at/on`.

Finally, re: installing, we should link to a _troubleshooting.md_ which lists common issues, directs people to IRC, and specifies what details they should share to get help. We can take care of that when we have such a document ready, of course.

Link to some instructions for fixing chrome, if possible, and fix the last line, and I'd say it's good for a PR.

**Comment by bitonator** [comment]
Chrome works fine, no settings changes needed, I'm on a Mac though, and that bug fix is reported on Windows, so not sure if that makes a difference.

s/at/on - done and pushed.

Fixing Chrome, will comb the docs for this and add.

Regarding the troubleshooting.md, I guess we'll have to collect all issues first, maybe just a text file dump from which I can write the doc.

**Comment by ansuz** [comment]
Chromium (Arch and Ubuntu) and chrome on linux (tested on Ubuntu) stopped working for me a while back, while I used to be able to `--enable-ipv6` at launch time. I prefer firefox anyway, though, so I didn't put too much time into it. Good to know it's not broken _everywhere_.

I'll see about writing up common issues somewhere accessible and we can see about getting that troubleshooting doc going.

Thanks for your help! I'll pull your fork in shortly.

See you on Hyperboria!

**Comment by ansuz** [comment]
Merged.

**Comment by bitonator** [comment]
awesome!

A small issue...i thought --enable-ipv6 was a compile flag, not a command line argument.

I'll fix this in the docs and let you know.
