### ISSUE TITLE
location in nodeinfo.json

### ISSUE THREAD

**Issue by ansuz** [hyperboria/docs#24]
I'm going to add an object to the spec, and label it as an experimental part of the format. anyone who disagrees should voice their opinion in this thread, and we'll revise it as necessary.

**Comment by ansuz** [comment]
[the relevant commit](https://github.com/hyperboria/docs/commit/0713be48f1ff86585c2a8d842e6f0d9ecfa40f7d)

**Comment by clehner** [comment]
I think `latitude` and `longitude` are useful. How is `location.url` meant to be different from 'http://' + `hostname`? If a node is in the US should they use state for `region` and city for `municipality`?

**Comment by cschmittiey** [comment]
:+1: no issues here

**Comment by thefinn93** [comment]
@clehner looks like the URL is meant to link to some mesh-local specific stuff, so eg the Seattle Meshnet nodes could link to the position of the node on our map.

**Comment by kpcyrd** [comment]
Since all keys are optional there are no issues for me.

**Comment by clehner** [comment]
> @clehner looks like the URL is meant to link to some mesh-local specific stuff, so eg the Seattle Meshnet nodes could link to the position of the node on our map.

Ok, that makes sense. I also notice that `url` is used in location whereas `uri`/`uris` is used in services. I assume `url` it to emphasize that the resource is something accessible in a web browser, vs. `uri` which could be hkp, telnet, cactus, …

**Comment by thefinn93** [comment]
Good point. In an effort to support the `cactus://` protocol, i vote we change it to `uri`. @ansuz ?

**Comment by ansuz** [comment]
works for me, someone else want to make the edit?

**Comment by ansuz** [comment]
fixed it.
