### ISSUE TITLE
fix naming schemes

### ISSUE THREAD

**Issue by ansuz** [hyperboria/docs#31]
Files have been named according to quite a few schemes:

* `tipsAndTricks.md`
* `shorewall_and_vpn_gateway_howto.md`
* `network-services.md`

I'm not terribly attached to any of them, but I think they should match.

Once we decide, `contributing.md` should note which one we expect for pull requests.

**Comment by thefinn93** [comment]
:+1: for `network-services.md` (lower case, hyphinated) naming scheme

**Comment by dansup** [comment]
:+1: for lower case, hyphinated

**Comment by ansuz** [comment]
:+1:
