### ISSUE TITLE
.html or .md

### ISSUE THREAD

**Issue by tsuckow** [hyperboria/docs#37]
Many links seem to use .html (which works on the website) and others use .md (which works on github).

I like that it works on github, which makes me wonder if the compiling script running somewhere should be changed to generate .md files instead of .html and have the server configured to serve them as html. Another option would be just redirecting back to github and only display it here.

Thoughts?

**Comment by thefinn93** [comment]
It should be `.md`, and any sort of markdown rendering that occurs (eg docs.meshwith.me) can be responsible for changing the extension. The rendering on docs.meshwith.me will do this automatically. I didn't realize people were linking to `.html`
