### ISSUE TITLE
New Fedora users confused by fedora.md

### ISSUE THREAD

**Issue by sdgathman** [hyperboria/docs#61]
So fedora.md was reverted to instructions for building cjdns yourself, which is fine, but it should at least *mention* that cjdns is a system package in Fedora.  New users hear about hyperboria, come here and try to follow the instructions (generally get stuck at the "edit cjdns.service" step), and give up.

If they aren't specifically setting out to build it themselves, the docs here are unhelpful.  I suggest a brief mention at the top to that effect:  

If you are not intending to build cjdns yourself, you are probably better off installing the Fedora system version.  "dnf install cjdns cjdns-selinux cjdns-tools"  and see README_Fedora.md in /usr/share/docs/cjdns

If you *do* want to build it yourself, proceed.

**Comment by thefinn93** [comment]
File a pull request?

**Comment by cschmittiey** [comment]
I went ahead and did it myself -- looks like @sdgathman had done a lot of work getting it documented before but it got lost in the shuffle. Credit for 99% of the info in my latest commit goes to him.

**Comment by sdgathman** [comment]
Thanks!  Looks good.
