### ISSUE TITLE
Expired cert for https://docs.meshwith.me

### ISSUE THREAD

**Issue by loooph** [hyperboria/docs#75]
Looks like the certificate expired on 2020-08-09.

**Comment by thefinn93** [comment]
It looks like IPv6 on that server isn't working and hasn't worked for a while, breaking the acme validation request.
* I rebooted the server (which fixed IPv6) and re-ran the certificate issuance job, which fixed the certificate for now.
* I have now added monitoring for the cert on that domain, so I'll be notified if the cert expires in the future.
